name: 'build-test'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - master
      - 'releases/*'
  pull_request:
    branches:
      - master
jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - uses: ./
        id: code-check
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}
          eslintConfig: .eslintrc.json
          eslintExt: ts
          eslintFiles: ./src
