name: 'build-test'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - master
      - 'releases/*'
jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          npm install
      - uses: ./
        id: code-check
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}
          eslintConfig: .eslintrc.json
          eslintExt: ts
          eslintFiles: ./src
